### ISSUE TITLE
[Style] 열차 날짜 및 옵션 선택 뷰 UI 

### ISSUE THREAD

**Issue by juri123123** [SOPT-all/35-COLLABORATION-iOS-KORAILTALK#5]
## 🔥 Issue 내용
열차 날짜 및 옵션 선택 뷰 UI 

## ✅ To-do
- [x] 열차 필터링 뷰 스택
- [x] 날짜 선택 시 날짜 가로스크롤
- [x] 모든열차/일반석/직통 선택 시 하단 바텀 시트 -> 공통으로 쓸 수 있게 컴포넌트화 하기
