### ISSUE TITLE
[Style] 좌석선택 기본화면 UI 구현

### ISSUE THREAD

**Issue by joho2022** [SOPT-all/35-COLLABORATION-iOS-KORAILTALK#8]
## 🔥 Issue 내용
좌석선택 기본화면 UI 구현

## ✅ To-do
- [x] 날짜,경로 헤더뷰 UI
- [x] 기차 객실 가로스크롤 컬렉션뷰 UI
- [x] 좌석선택 헤더뷰 UI
- [x] 좌석선택 세로스크롤 컬렉션뷰 UI
